### ISSUE TITLE
Error when trying to review moved spec

### ISSUE THREAD

**Issue by vinhowe** [vinhowe/lifesystem#27]
**Description**:
When trying to review a recently moved spec, Perora spits this out instead and dies tragically:
```
Traceback (most recent call last):
  File "app.py", line 31, in <module>
    main()
  File "app.py", line 27, in main
    programs[selected_program]()
  File "/home/vin/dev/lifesystem/perora/spec.py", line 739, in spec
    run_command(command)
  File "/home/vin/dev/lifesystem/perora/spec.py", line 408, in run_command
    commands[command](args[1])
  File "/home/vin/dev/lifesystem/perora/spec.py", line 248, in _command_review_spec_element
    _edit_spec_review_doc_side_by_side(slug, date_str)
  File "/home/vin/dev/lifesystem/perora/spec.py", line 499, in _edit_spec_review_doc_side_by_side
    edit_documents(spec_service_name, [spec_slug, review_slug], key)
  File "/home/vin/dev/lifesystem/perora/document_manager.py", line 228, in edit_documents
    temp_edit_file.write(decrypted_content)
  File "/usr/lib/python3.7/tempfile.py", line 620, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'NoneType'
```

**To reproduce:**
Create a spec (`new`), `move` it, and try to `review` it.

**Expected behavior:**
Spec should open side-by-side with review pane.

**Comment by vinhowe** [comment]
Closing spec issues
